# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Applied Data Visualization
tagline:          MAS.XXX
description:      'Principles and practice of modern data visualization.'
url:              http://viz.media.mit.edu
baseurl:          /

author:
  name:           'Collective Learning Group'
  url:            https://collective.media.mit.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MacroConnections/applied-data-viz
